# Generated by Django 3.2.8 on 2021-11-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('img_path1', models.CharField(max_length=200)),
                ('img_path2', models.CharField(max_length=200)),
                ('img_path3', models.CharField(max_length=200)),
            ],
        ),
    ]
