# Generated by Django 3.2.8 on 2021-11-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img_path1',
            new_name='dir_path',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_path2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='img_path3',
        ),
    ]
