# Generated by Django 3.2.8 on 2021-11-03 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0002_auto_20211103_1355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='m_user',
        ),
    ]
