# Generated by Django 3.2.8 on 2021-11-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0003_rename_user_m_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='w_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('dir_path', models.CharField(max_length=200)),
            ],
        ),
    ]
