# Generated by Django 3.2.8 on 2021-11-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0004_w_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='images/', verbose_name='1枚目')),
                ('img2', models.ImageField(upload_to='images/', verbose_name='2枚目')),
                ('img3', models.ImageField(upload_to='images/', verbose_name='3枚目')),
            ],
        ),
    ]
