# Generated by Django 3.2.8 on 2021-11-12 13:51

from django.db import migrations, models
import reco.models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0006_auto_20211112_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='img1',
            field=models.ImageField(storage=reco.models.OverwriteStorage(location='C:\\Users\\norimasa\\recom\\web\\mysite\\media'), upload_to='images/', verbose_name='img_1'),
        ),
        migrations.AlterField(
            model_name='user_img',
            name='img2',
            field=models.ImageField(storage=reco.models.OverwriteStorage(location='C:\\Users\\norimasa\\recom\\web\\mysite\\media'), upload_to='images/', verbose_name='img_2'),
        ),
        migrations.AlterField(
            model_name='user_img',
            name='img3',
            field=models.ImageField(storage=reco.models.OverwriteStorage(location='C:\\Users\\norimasa\\recom\\web\\mysite\\media'), upload_to='images/', verbose_name='img_3'),
        ),
    ]
