# Generated by Django 3.2.8 on 2021-11-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0007_auto_20211112_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_img',
            name='img2',
            field=models.ImageField(upload_to='images/', verbose_name='img_2'),
        ),
        migrations.AlterField(
            model_name='user_img',
            name='img3',
            field=models.ImageField(upload_to='images/', verbose_name='img_3'),
        ),
    ]
