# Generated by Django 3.2.8 on 2021-11-19 12:18

from django.db import migrations, models
import reco.models


class Migration(migrations.Migration):

    dependencies = [
        ('reco', '0009_single_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_img',
            name='img',
            field=models.ImageField(storage=reco.models.OverwriteStorage(location='C:\\Users\\norimasa\\recom\\web\\mysite\\media'), upload_to='SImg/', verbose_name='img_1'),
        ),
    ]
